### ISSUE TITLE
How does the title case conversion work?

### ISSUE THREAD

**Issue by GaurangTandon** [ubery/change-case#3]
I find the title case conversion extremely useful. Especially how it leaves the words like "of" and "and" in lowercase.
I was hoping to code something similar but am stumped on how to handle these words. At first I thought of just using a simple RegEx to check for such trivial prepositions, but that is a brute force method, and I was interested in the creative code you may have employed.

Unfortunately, I have yet not been able to figure out what code is being used. From what I have seen, most of your cases are stored in `/scripts/cases.js` which imports `toTitleCase` from `'to-title-case'`. This is based on [a work by Blake Embrey](https://github.com/blakeembrey/title-case) which has the following code:

```
return noCase(value, locale).replace(/^.| ./g, function (m) {
    return upperCase(m, locale)
})
```

Heading over to the [`noCase` function](https://github.com/blakeembrey/no-case/blob/master/no-case.js) doesn't seem to mention any occurrence of `"of"`, `"and"`, etc. So, I am stuck.

Could you please help a fellow coder? Thanks!

**Comment by bartoszlorek** [comment]
Case functions inside `cases.js` file are based (with modifications) on Blake Embrey's source, but imported one not. Blake Embrey's `titleCase` was an initial approach, but as you know, it isn't handling conjunctions. The function `toTitleCase` is a dependency of [to-title-case](https://github.com/ianstormtaylor/to-title-case) repository by Ian Storm Taylor. It uses a [title-case-minors](https://github.com/ianstormtaylor/title-case-minors) array of previously prepared words from English.
